export const elements = {
    cells: document.querySelectorAll(".cell"),
    winnerText: document.querySelector(".winner"),
    restartBtn: document.querySelector(".restartBtn"),
    playBtn: document.getElementById("play-btn"),
    startScreen: document.getElementById("start-screen"),
    gameContainer: document.getElementById("game-container"),
    choiceOverlay: document.getElementById("choice-overlay"),
    nameOverlay: document.getElementById("name-overlay"),
    resultsOverlayContent: document.getElementById("result-overlay-content"),
    aiBtn: document.getElementById("ai-btn"),
    playerBtn: document.getElementById("player-btn"),
    resultsOverlay: document.getElementById("result-overlay"),
    easyBtn: document.getElementById("easy-btn"),
    mediumBtn: document.getElementById("medium-btn"),
    hardBtn: document.getElementById("hard-btn"),
    currentDifficultyText: document.getElementById("current-difficulty"),
    goBackBtn: document.querySelector(".goBackBtn"),
    player1NameInput: document.getElementById("player1-name-input"),
    player2NameInput: document.getElementById("player2-name-input"),
    startGameBtn: document.getElementById("start-game-btn"),
    themeSwitchBtn: document.getElementById("theme-switch"),
};

